### ISSUE TITLE
Acerca del conector Whatsapp

### ISSUE THREAD

**Issue by mendozada** [gabriel-tandil/whatsapp-connector#1]
Hola Gabriel ,  estoy viendo el codigo de este conector y te consulto si tendria algun ejemplo funcionando. Estoy buscando enviar msj a wsp de una bd de clientes . 
Te agredezco cualquier ayuda. Saludos  . 

Diego.

**Comment by gabriel-tandil** [comment]
Hello!
Sorry, I currently have no examples available to publish and not much time to document this development.
Greetings
